version: '3.0'

services:
  diabetes-helper-frontend:
    image: diabetes-helper-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv
    ports:
      - 80:4200
    command: [ "ng", "serve", "--host", "0.0.0.0" ]
